create schema fortnite_bot;
revoke all on schema fortnite_bot from public, anon, authenticated;
create table fortnite_bot.schema_version(singleton boolean primary key default true check(singleton),version text not null);
insert into fortnite_bot.schema_version values(true,'20260901000000');
create table fortnite_bot.sessions(message_id bigint primary key,chat_id bigint not null,initiator_id bigint not null,initiator_name text not null,is_complete boolean not null default false,is_expired boolean not null default false,is_closed boolean not null default false,style integer not null default 0,created_at timestamptz not null,completed_at timestamptz,time_slots jsonb not null default '[]',tag_line jsonb not null default '{}',llm_header text);
create table fortnite_bot.responses(message_id bigint not null references fortnite_bot.sessions(message_id),user_id bigint not null,user_name text not null,response text not null check(response in ('go','pass')),responded_at timestamptz not null,joined_at timestamptz,time_slot text,is_bot boolean not null default false,primary key(message_id,user_id));
create table fortnite_bot.chat_features(chat_id bigint not null,feature text not null,enabled boolean not null default false,value double precision,primary key(chat_id,feature));
create table fortnite_bot.afk_mutes(chat_id bigint not null,user_id bigint not null,muted_until timestamptz not null,primary key(chat_id,user_id));
create table fortnite_bot.roast_state(chat_id bigint primary key,history_json jsonb not null default '[]',roast_msgs_json jsonb not null default '[]',last_roast timestamptz);
create table fortnite_bot.epic_links(chat_id bigint not null,user_id bigint not null,user_name text not null,epic_name text not null,epic_account_id text not null,linked_at timestamptz not null,primary key(chat_id,user_id));
create table fortnite_bot.squad_snapshots(epic_account_id text not null,fetched_at timestamptz not null,matches integer not null,wins integer not null,kills integer not null,deaths_est integer not null,kd double precision not null,overall_matches integer,overall_wins integer,overall_kills integer,overall_deaths_est integer,overall_kd double precision,primary key(epic_account_id,fetched_at));
create index sessions_chat_created_idx on fortnite_bot.sessions(chat_id,created_at desc);
create index responses_message_idx on fortnite_bot.responses(message_id);
create index responses_recent_idx on fortnite_bot.responses(user_id,responded_at desc) where response='go' and not is_bot;
create index epic_links_chat_idx on fortnite_bot.epic_links(chat_id);
create index snapshots_account_time_idx on fortnite_bot.squad_snapshots(epic_account_id,fetched_at desc);
alter table fortnite_bot.sessions enable row level security;
alter table fortnite_bot.responses enable row level security;
alter table fortnite_bot.chat_features enable row level security;
alter table fortnite_bot.afk_mutes enable row level security;
alter table fortnite_bot.roast_state enable row level security;
alter table fortnite_bot.epic_links enable row level security;
alter table fortnite_bot.squad_snapshots enable row level security;
revoke all on all tables in schema fortnite_bot from public,anon,authenticated;
